// Generated by tools/gen_messages.mjs from svelte/src/compiler/warnings.js. Do not edit.
#![allow(clippy::all)]

/// A warning before it is attached to a position
pub struct W {
	pub code: &'static str,
	pub message: String,
}

pub fn a11y_accesskey() -> W {
	W { code: "a11y_accesskey", message: format!("Avoid using accesskey\nhttps://svelte.dev/e/a11y_accesskey") }
}

pub fn a11y_aria_activedescendant_has_tabindex() -> W {
	W { code: "a11y_aria_activedescendant_has_tabindex", message: format!("An element with an aria-activedescendant attribute should have a tabindex value\nhttps://svelte.dev/e/a11y_aria_activedescendant_has_tabindex") }
}

pub fn a11y_aria_attributes(name: &str) -> W {
	W { code: "a11y_aria_attributes", message: format!("`<{}>` should not have aria-* attributes\nhttps://svelte.dev/e/a11y_aria_attributes", name) }
}

pub fn a11y_autocomplete_valid(value: &str, r#type: &str) -> W {
	W { code: "a11y_autocomplete_valid", message: format!("'{}' is an invalid value for 'autocomplete' on `<input type=\"{}\">`\nhttps://svelte.dev/e/a11y_autocomplete_valid", value, r#type) }
}

pub fn a11y_autofocus() -> W {
	W { code: "a11y_autofocus", message: format!("Avoid using autofocus\nhttps://svelte.dev/e/a11y_autofocus") }
}

pub fn a11y_click_events_have_key_events(element: &str) -> W {
	W { code: "a11y_click_events_have_key_events", message: format!("Visible, non-interactive element `<{}>` with a click event must be accompanied by a keyboard event handler. Consider whether an interactive element such as `<button type=\"button\">` or `<a>` might be more appropriate\nhttps://svelte.dev/e/a11y_click_events_have_key_events", element) }
}

pub fn a11y_consider_explicit_label() -> W {
	W { code: "a11y_consider_explicit_label", message: format!("Buttons and links should either contain text or have an `aria-label`, `aria-labelledby` or `title` attribute\nhttps://svelte.dev/e/a11y_consider_explicit_label") }
}

pub fn a11y_distracting_elements(name: &str) -> W {
	W { code: "a11y_distracting_elements", message: format!("Avoid `<{}>` elements\nhttps://svelte.dev/e/a11y_distracting_elements", name) }
}

pub fn a11y_figcaption_index() -> W {
	W { code: "a11y_figcaption_index", message: format!("`<figcaption>` must be first or last child of `<figure>`\nhttps://svelte.dev/e/a11y_figcaption_index") }
}

pub fn a11y_figcaption_parent() -> W {
	W { code: "a11y_figcaption_parent", message: format!("`<figcaption>` must be an immediate child of `<figure>`\nhttps://svelte.dev/e/a11y_figcaption_parent") }
}

pub fn a11y_hidden(name: &str) -> W {
	W { code: "a11y_hidden", message: format!("`<{}>` element should not be hidden\nhttps://svelte.dev/e/a11y_hidden", name) }
}

pub fn a11y_img_redundant_alt() -> W {
	W { code: "a11y_img_redundant_alt", message: format!("Screenreaders already announce `<img>` elements as an image\nhttps://svelte.dev/e/a11y_img_redundant_alt") }
}

pub fn a11y_incorrect_aria_attribute_type(attribute: &str, r#type: &str) -> W {
	W { code: "a11y_incorrect_aria_attribute_type", message: format!("The value of '{}' must be a {}\nhttps://svelte.dev/e/a11y_incorrect_aria_attribute_type", attribute, r#type) }
}

pub fn a11y_incorrect_aria_attribute_type_boolean(attribute: &str) -> W {
	W { code: "a11y_incorrect_aria_attribute_type_boolean", message: format!("The value of '{}' must be either 'true' or 'false'. It cannot be empty\nhttps://svelte.dev/e/a11y_incorrect_aria_attribute_type_boolean", attribute) }
}

pub fn a11y_incorrect_aria_attribute_type_id(attribute: &str) -> W {
	W { code: "a11y_incorrect_aria_attribute_type_id", message: format!("The value of '{}' must be a string that represents a DOM element ID\nhttps://svelte.dev/e/a11y_incorrect_aria_attribute_type_id", attribute) }
}

pub fn a11y_incorrect_aria_attribute_type_idlist(attribute: &str) -> W {
	W { code: "a11y_incorrect_aria_attribute_type_idlist", message: format!("The value of '{}' must be a space-separated list of strings that represent DOM element IDs\nhttps://svelte.dev/e/a11y_incorrect_aria_attribute_type_idlist", attribute) }
}

pub fn a11y_incorrect_aria_attribute_type_integer(attribute: &str) -> W {
	W { code: "a11y_incorrect_aria_attribute_type_integer", message: format!("The value of '{}' must be an integer\nhttps://svelte.dev/e/a11y_incorrect_aria_attribute_type_integer", attribute) }
}

pub fn a11y_incorrect_aria_attribute_type_token(attribute: &str, values: &str) -> W {
	W { code: "a11y_incorrect_aria_attribute_type_token", message: format!("The value of '{}' must be exactly one of {}\nhttps://svelte.dev/e/a11y_incorrect_aria_attribute_type_token", attribute, values) }
}

pub fn a11y_incorrect_aria_attribute_type_tokenlist(attribute: &str, values: &str) -> W {
	W { code: "a11y_incorrect_aria_attribute_type_tokenlist", message: format!("The value of '{}' must be a space-separated list of one or more of {}\nhttps://svelte.dev/e/a11y_incorrect_aria_attribute_type_tokenlist", attribute, values) }
}

pub fn a11y_incorrect_aria_attribute_type_tristate(attribute: &str) -> W {
	W { code: "a11y_incorrect_aria_attribute_type_tristate", message: format!("The value of '{}' must be exactly one of true, false, or mixed\nhttps://svelte.dev/e/a11y_incorrect_aria_attribute_type_tristate", attribute) }
}

pub fn a11y_interactive_supports_focus(role: &str) -> W {
	W { code: "a11y_interactive_supports_focus", message: format!("Elements with the '{}' interactive role must have a tabindex value\nhttps://svelte.dev/e/a11y_interactive_supports_focus", role) }
}

pub fn a11y_invalid_attribute(href_value: &str, href_attribute: &str) -> W {
	W { code: "a11y_invalid_attribute", message: format!("'{}' is not a valid {} attribute\nhttps://svelte.dev/e/a11y_invalid_attribute", href_value, href_attribute) }
}

pub fn a11y_label_has_associated_control() -> W {
	W { code: "a11y_label_has_associated_control", message: format!("A form label must be associated with a control\nhttps://svelte.dev/e/a11y_label_has_associated_control") }
}

pub fn a11y_media_has_caption() -> W {
	W { code: "a11y_media_has_caption", message: format!("`<video>` elements must have a `<track kind=\"captions\">`\nhttps://svelte.dev/e/a11y_media_has_caption") }
}

pub fn a11y_misplaced_role(name: &str) -> W {
	W { code: "a11y_misplaced_role", message: format!("`<{}>` should not have role attribute\nhttps://svelte.dev/e/a11y_misplaced_role", name) }
}

pub fn a11y_misplaced_scope() -> W {
	W { code: "a11y_misplaced_scope", message: format!("The scope attribute should only be used with `<th>` elements\nhttps://svelte.dev/e/a11y_misplaced_scope") }
}

pub fn a11y_missing_attribute(name: &str, article: &str, sequence: &str) -> W {
	W { code: "a11y_missing_attribute", message: format!("`<{}>` element should have {} {} attribute\nhttps://svelte.dev/e/a11y_missing_attribute", name, article, sequence) }
}

pub fn a11y_missing_content(name: &str) -> W {
	W { code: "a11y_missing_content", message: format!("`<{}>` element should contain text\nhttps://svelte.dev/e/a11y_missing_content", name) }
}

pub fn a11y_mouse_events_have_key_events(event: &str, accompanied_by: &str) -> W {
	W { code: "a11y_mouse_events_have_key_events", message: format!("'{}' event must be accompanied by '{}' event\nhttps://svelte.dev/e/a11y_mouse_events_have_key_events", event, accompanied_by) }
}

pub fn a11y_no_abstract_role(role: &str) -> W {
	W { code: "a11y_no_abstract_role", message: format!("Abstract role '{}' is forbidden\nhttps://svelte.dev/e/a11y_no_abstract_role", role) }
}

pub fn a11y_no_interactive_element_to_noninteractive_role(element: &str, role: &str) -> W {
	W { code: "a11y_no_interactive_element_to_noninteractive_role", message: format!("`<{}>` cannot have role '{}'\nhttps://svelte.dev/e/a11y_no_interactive_element_to_noninteractive_role", element, role) }
}

pub fn a11y_no_noninteractive_element_interactions(element: &str) -> W {
	W { code: "a11y_no_noninteractive_element_interactions", message: format!("Non-interactive element `<{}>` should not be assigned mouse or keyboard event listeners\nhttps://svelte.dev/e/a11y_no_noninteractive_element_interactions", element) }
}

pub fn a11y_no_noninteractive_element_to_interactive_role(element: &str, role: &str) -> W {
	W { code: "a11y_no_noninteractive_element_to_interactive_role", message: format!("Non-interactive element `<{}>` cannot have interactive role '{}'\nhttps://svelte.dev/e/a11y_no_noninteractive_element_to_interactive_role", element, role) }
}

pub fn a11y_no_noninteractive_tabindex() -> W {
	W { code: "a11y_no_noninteractive_tabindex", message: format!("noninteractive element cannot have nonnegative tabIndex value\nhttps://svelte.dev/e/a11y_no_noninteractive_tabindex") }
}

pub fn a11y_no_redundant_roles(role: &str) -> W {
	W { code: "a11y_no_redundant_roles", message: format!("Redundant role '{}'\nhttps://svelte.dev/e/a11y_no_redundant_roles", role) }
}

pub fn a11y_no_static_element_interactions(element: &str, handler: &str) -> W {
	W { code: "a11y_no_static_element_interactions", message: format!("`<{}>` with a {} handler must have an ARIA role\nhttps://svelte.dev/e/a11y_no_static_element_interactions", element, handler) }
}

pub fn a11y_positive_tabindex() -> W {
	W { code: "a11y_positive_tabindex", message: format!("Avoid tabindex values above zero\nhttps://svelte.dev/e/a11y_positive_tabindex") }
}

pub fn a11y_role_has_required_aria_props(role: &str, props: &str) -> W {
	W { code: "a11y_role_has_required_aria_props", message: format!("Elements with the ARIA role \"{}\" must have the following attributes defined: {}\nhttps://svelte.dev/e/a11y_role_has_required_aria_props", role, props) }
}

pub fn a11y_role_supports_aria_props(attribute: &str, role: &str) -> W {
	W { code: "a11y_role_supports_aria_props", message: format!("The attribute '{}' is not supported by the role '{}'\nhttps://svelte.dev/e/a11y_role_supports_aria_props", attribute, role) }
}

pub fn a11y_role_supports_aria_props_implicit(attribute: &str, role: &str, name: &str) -> W {
	W { code: "a11y_role_supports_aria_props_implicit", message: format!("The attribute '{}' is not supported by the role '{}'. This role is implicit on the element `<{}>`\nhttps://svelte.dev/e/a11y_role_supports_aria_props_implicit", attribute, role, name) }
}

pub fn a11y_unknown_aria_attribute(attribute: &str, suggestion: Option<&str>) -> W {
	W { code: "a11y_unknown_aria_attribute", message: match suggestion { Some(v) if !v.is_empty() => format!("Unknown aria attribute 'aria-{}'. Did you mean '{}'?\nhttps://svelte.dev/e/a11y_unknown_aria_attribute", attribute, v), _ => format!("Unknown aria attribute 'aria-{}'\nhttps://svelte.dev/e/a11y_unknown_aria_attribute", attribute) } }
}

pub fn a11y_unknown_role(role: &str, suggestion: Option<&str>) -> W {
	W { code: "a11y_unknown_role", message: match suggestion { Some(v) if !v.is_empty() => format!("Unknown role '{}'. Did you mean '{}'?\nhttps://svelte.dev/e/a11y_unknown_role", role, v), _ => format!("Unknown role '{}'\nhttps://svelte.dev/e/a11y_unknown_role", role) } }
}

pub fn bidirectional_control_characters() -> W {
	W { code: "bidirectional_control_characters", message: format!("A bidirectional control character was detected in your code. These characters can be used to alter the visual direction of your code and could have unintended consequences\nhttps://svelte.dev/e/bidirectional_control_characters") }
}

pub fn legacy_code(code: &str, suggestion: &str) -> W {
	W { code: "legacy_code", message: format!("`{}` is no longer valid — please use `{}` instead\nhttps://svelte.dev/e/legacy_code", code, suggestion) }
}

pub fn unknown_code(code: &str, suggestion: Option<&str>) -> W {
	W { code: "unknown_code", message: match suggestion { Some(v) if !v.is_empty() => format!("`{}` is not a recognised code (did you mean `{}`?)\nhttps://svelte.dev/e/unknown_code", code, v), _ => format!("`{}` is not a recognised code\nhttps://svelte.dev/e/unknown_code", code) } }
}

pub fn options_deprecated_accessors() -> W {
	W { code: "options_deprecated_accessors", message: format!("The `accessors` option has been deprecated. It will have no effect in runes mode\nhttps://svelte.dev/e/options_deprecated_accessors") }
}

pub fn options_deprecated_immutable() -> W {
	W { code: "options_deprecated_immutable", message: format!("The `immutable` option has been deprecated. It will have no effect in runes mode\nhttps://svelte.dev/e/options_deprecated_immutable") }
}

pub fn options_missing_custom_element() -> W {
	W { code: "options_missing_custom_element", message: format!("The `customElement` option is used when generating a custom element. Did you forget the `customElement: true` compile option?\nhttps://svelte.dev/e/options_missing_custom_element") }
}

pub fn options_removed_enable_sourcemap() -> W {
	W { code: "options_removed_enable_sourcemap", message: format!("The `enableSourcemap` option has been removed. Source maps are always generated now, and tooling can choose to ignore them\nhttps://svelte.dev/e/options_removed_enable_sourcemap") }
}

pub fn options_removed_hydratable() -> W {
	W { code: "options_removed_hydratable", message: format!("The `hydratable` option has been removed. Svelte components are always hydratable now\nhttps://svelte.dev/e/options_removed_hydratable") }
}

pub fn options_removed_loop_guard_timeout() -> W {
	W { code: "options_removed_loop_guard_timeout", message: format!("The `loopGuardTimeout` option has been removed\nhttps://svelte.dev/e/options_removed_loop_guard_timeout") }
}

pub fn options_renamed_ssr_dom() -> W {
	W { code: "options_renamed_ssr_dom", message: format!("`generate: \"dom\"` and `generate: \"ssr\"` options have been renamed to \"client\" and \"server\" respectively\nhttps://svelte.dev/e/options_renamed_ssr_dom") }
}

pub fn custom_element_props_identifier() -> W {
	W { code: "custom_element_props_identifier", message: format!("Using a rest element or a non-destructured declaration with `$props()` means that Svelte can't infer what properties to expose when creating a custom element. Consider destructuring all the props or explicitly specifying the `customElement.props` option.\nhttps://svelte.dev/e/custom_element_props_identifier") }
}

pub fn export_let_unused(name: &str) -> W {
	W { code: "export_let_unused", message: format!("Component has unused export property '{}'. If it is for external reference only, please consider using `export const {}`\nhttps://svelte.dev/e/export_let_unused", name, name) }
}

pub fn legacy_component_creation() -> W {
	W { code: "legacy_component_creation", message: format!("Svelte 5 components are no longer classes. Instantiate them using `mount` or `hydrate` (imported from 'svelte') instead.\nhttps://svelte.dev/e/legacy_component_creation") }
}

pub fn non_reactive_update(name: &str) -> W {
	W { code: "non_reactive_update", message: format!("`{}` is updated, but is not declared with `$state(...)`. Changing its value will not correctly trigger updates\nhttps://svelte.dev/e/non_reactive_update", name) }
}

pub fn perf_avoid_inline_class() -> W {
	W { code: "perf_avoid_inline_class", message: format!("Avoid 'new class' — instead, declare the class at the top level scope\nhttps://svelte.dev/e/perf_avoid_inline_class") }
}

pub fn perf_avoid_nested_class() -> W {
	W { code: "perf_avoid_nested_class", message: format!("Avoid declaring classes below the top level scope\nhttps://svelte.dev/e/perf_avoid_nested_class") }
}

pub fn reactive_declaration_invalid_placement() -> W {
	W { code: "reactive_declaration_invalid_placement", message: format!("Reactive declarations only exist at the top level of the instance script\nhttps://svelte.dev/e/reactive_declaration_invalid_placement") }
}

pub fn reactive_declaration_module_script_dependency() -> W {
	W { code: "reactive_declaration_module_script_dependency", message: format!("Reassignments of module-level declarations will not cause reactive statements to update\nhttps://svelte.dev/e/reactive_declaration_module_script_dependency") }
}

pub fn state_referenced_locally(name: &str, r#type: &str) -> W {
	W { code: "state_referenced_locally", message: format!("This reference only captures the initial value of `{}`. Did you mean to reference it inside a {} instead?\nhttps://svelte.dev/e/state_referenced_locally", name, r#type) }
}

pub fn store_rune_conflict(name: &str) -> W {
	W { code: "store_rune_conflict", message: format!("It looks like you're using the `${}` rune, but there is a local binding called `{}`. Referencing a local variable with a `$` prefix will create a store subscription. Please rename `{}` to avoid the ambiguity\nhttps://svelte.dev/e/store_rune_conflict", name, name, name) }
}

pub fn css_unused_selector(name: &str) -> W {
	W { code: "css_unused_selector", message: format!("Unused CSS selector \"{}\"\nhttps://svelte.dev/e/css_unused_selector", name) }
}

pub fn attribute_avoid_is() -> W {
	W { code: "attribute_avoid_is", message: format!("The \"is\" attribute is not supported cross-browser and should be avoided\nhttps://svelte.dev/e/attribute_avoid_is") }
}

pub fn attribute_global_event_reference(name: &str) -> W {
	W { code: "attribute_global_event_reference", message: format!("You are referencing `globalThis.{}`. Did you forget to declare a variable with that name?\nhttps://svelte.dev/e/attribute_global_event_reference", name) }
}

pub fn attribute_illegal_colon() -> W {
	W { code: "attribute_illegal_colon", message: format!("Attributes should not contain ':' characters to prevent ambiguity with Svelte directives\nhttps://svelte.dev/e/attribute_illegal_colon") }
}

pub fn attribute_invalid_property_name(wrong: &str, right: &str) -> W {
	W { code: "attribute_invalid_property_name", message: format!("'{}' is not a valid HTML attribute. Did you mean '{}'?\nhttps://svelte.dev/e/attribute_invalid_property_name", wrong, right) }
}

pub fn attribute_quoted() -> W {
	W { code: "attribute_quoted", message: format!("Quoted attributes on components and custom elements will be stringified in a future version of Svelte. If this isn't what you want, remove the quotes\nhttps://svelte.dev/e/attribute_quoted") }
}

pub fn bind_invalid_each_rest(name: &str) -> W {
	W { code: "bind_invalid_each_rest", message: format!("The rest operator (...) will create a new object and binding '{}' with the original object will not work\nhttps://svelte.dev/e/bind_invalid_each_rest", name) }
}

pub fn block_empty() -> W {
	W { code: "block_empty", message: format!("Empty block\nhttps://svelte.dev/e/block_empty") }
}

pub fn component_name_lowercase(name: &str) -> W {
	W { code: "component_name_lowercase", message: format!("`<{}>` will be treated as an HTML element unless it begins with a capital letter\nhttps://svelte.dev/e/component_name_lowercase", name) }
}

pub fn element_implicitly_closed(tag: &str, closing: &str) -> W {
	W { code: "element_implicitly_closed", message: format!("This element is implicitly closed by the following `{}`, which can cause an unexpected DOM structure. Add an explicit `{}` to avoid surprises.\nhttps://svelte.dev/e/element_implicitly_closed", tag, closing) }
}

pub fn element_invalid_self_closing_tag(name: &str) -> W {
	W { code: "element_invalid_self_closing_tag", message: format!("Self-closing HTML tags for non-void elements are ambiguous — use `<{} ...></{}>` rather than `<{} ... />`\nhttps://svelte.dev/e/element_invalid_self_closing_tag", name, name, name) }
}

pub fn event_directive_deprecated(name: &str) -> W {
	W { code: "event_directive_deprecated", message: format!("Using `on:{}` to listen to the {} event is deprecated. Use the event attribute `on{}` instead\nhttps://svelte.dev/e/event_directive_deprecated", name, name, name) }
}

pub fn node_invalid_placement_ssr(message: &str) -> W {
	W { code: "node_invalid_placement_ssr", message: format!("{}. When rendering this component on the server, the resulting HTML will be modified by the browser (by moving, removing, or inserting elements), likely resulting in a `hydration_mismatch` warning\nhttps://svelte.dev/e/node_invalid_placement_ssr", message) }
}

pub fn script_context_deprecated() -> W {
	W { code: "script_context_deprecated", message: format!("`context=\"module\"` is deprecated, use the `module` attribute instead\nhttps://svelte.dev/e/script_context_deprecated") }
}

pub fn script_unknown_attribute() -> W {
	W { code: "script_unknown_attribute", message: format!("Unrecognised attribute — should be one of `generics`, `lang` or `module`. If this exists for a preprocessor, ensure that the preprocessor removes it\nhttps://svelte.dev/e/script_unknown_attribute") }
}

pub fn slot_element_deprecated() -> W {
	W { code: "slot_element_deprecated", message: format!("Using `<slot>` to render parent content is deprecated. Use `{{@render ...}}` tags instead\nhttps://svelte.dev/e/slot_element_deprecated") }
}

pub fn svelte_component_deprecated() -> W {
	W { code: "svelte_component_deprecated", message: format!("`<svelte:component>` is deprecated in runes mode — components are dynamic by default\nhttps://svelte.dev/e/svelte_component_deprecated") }
}

pub fn svelte_element_invalid_this() -> W {
	W { code: "svelte_element_invalid_this", message: format!("`this` should be an `{{expression}}`. Using a string attribute value will cause an error in future versions of Svelte\nhttps://svelte.dev/e/svelte_element_invalid_this") }
}

pub fn svelte_self_deprecated(name: &str, basename: &str) -> W {
	W { code: "svelte_self_deprecated", message: format!("`<svelte:self>` is deprecated — use self-imports (e.g. `import {} from './{}'`) instead\nhttps://svelte.dev/e/svelte_self_deprecated", name, basename) }
}

