// Generates src/errors.rs from Svelte's generated errors.js, for the codes the parser uses.
import fs from 'node:fs';
const [errors_js, out, ...codes] = process.argv.slice(2);
const src = fs.readFileSync(errors_js, 'utf-8');
const re = /export function (\w+)\(node(?:, )?([^)]*)\) \{\n\te\(node, '\w+', (`(?:\\.|[^`\\])*`|'[^']*')\);/g;
const fns = new Map();
for (const m of src.matchAll(re)) fns.set(m[1], { params: m[2] ? m[2].split(', ') : [], tpl: m[3] });
let rs = '// Generated by tools/gen_errors.mjs from svelte/src/compiler/errors.js. Do not edit.\n#![allow(clippy::all)]\nuse crate::error::{CompileError, Loc};\n\n';
for (const code of codes) {
	const f = fns.get(code);
	if (!f) throw new Error('missing ' + code);
	const ident = (p) => (p === 'type' ? 'r#type' : p);
	const params = f.params.map((p) => `${ident(p)}: &str`).join(', ');
	let body = f.tpl.slice(1, -1).replace(/\\n/g, "\n").replace(/\\`/g, "`").replace(/\\\\/g, "\\");
	const args = [];
	body = body.replace(/[{}]/g, (c) => c + c).replace(/\$\{\{(\w+)\}\}/g, (_, n) => (args.push(n), '{}'));
	const lit = JSON.stringify(body).replace(/\{\}/g, '{}');
	rs += `pub fn ${code}(node: impl Into<Loc>${params ? ', ' + params : ''}) -> CompileError {\n\tCompileError::new(node.into(), "${code}", format!(${lit}${args.map((a) => ', ' + ident(a)).join('')}))\n}\n\n`;
}
fs.writeFileSync(out, rs);
