// Generates src/css_lint/data.rs from the CSS/HTML data bundled in svelte-check (the copy of
// vscode-css-languageservice / vscode-html-languageservice it ships, plus svelte-language-server's
// custom data provider), merged the way `CSSDataManager.collectData` does (first provider wins).
//
// usage: node tools/gen_css_data.mjs [out.rs]   (SVELTE_CHECK=path/to/svelte-check/dist/src/index.js)
import fs from 'node:fs';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { loadSvelteCheck } = require('../oracle/load_svelte_check.cjs');

const out = process.argv[2] ?? new URL('../src/css_lint/data.rs', import.meta.url).pathname;
const { cssLanguageService, getDefaultHTMLDataProvider, svelteCustomDataProvider } = loadSvelteCheck();
const providers = [cssLanguageService.getDefaultCSSDataProvider(), svelteCustomDataProvider];

const properties = new Map();
const atDirectives = new Map();
for (const p of providers) {
    for (const prop of p.provideProperties()) if (!properties.has(prop.name)) properties.set(prop.name, prop);
    for (const at of p.provideAtDirectives()) if (!atDirectives.has(at.name)) atDirectives.set(at.name, at);
}
const cmp = (a, b) => Buffer.compare(Buffer.from(a), Buffer.from(b));
const voidElements = getDefaultHTMLDataProvider()
    .provideTags()
    .filter((t) => t.void)
    .map((t) => t.name);

let rs = '// Generated by tools/gen_css_data.mjs from the data bundled in svelte-check. Do not edit.\n\n';
rs += '/// `(name, standard)` for every CSS property, sorted by name. `standard` is `!status || status === "standard"`.\n';
rs += 'pub static PROPERTIES: &[(&str, bool)] = &[\n';
for (const name of [...properties.keys()].sort(cmp)) {
    const status = properties.get(name).status;
    rs += `    (${JSON.stringify(name)}, ${!status || status === 'standard'}),\n`;
}
rs += '];\n\n/// Names of the known at-rules, sorted.\npub static AT_DIRECTIVES: &[&str] = &[\n';
for (const name of [...atDirectives.keys()].sort(cmp)) rs += `    ${JSON.stringify(name)},\n`;
rs += '];\n\n/// HTML void elements (vscode-html-languageservice data), sorted.\npub static VOID_ELEMENTS: &[&str] = &[\n';
for (const name of voidElements.sort(cmp)) rs += `    ${JSON.stringify(name)},\n`;
rs += '];\n';
fs.writeFileSync(out, rs);
console.error(`${properties.size} properties, ${atDirectives.size} at-rules, ${voidElements.length} void elements -> ${out}`);
