// Generates src/analyze/a11y_data.rs: the tables Svelte's a11y checks compute from
// aria-query / axobject-query (phases/2-analyze/visitors/shared/a11y/constants.js).
//   cd oracle && node ../tools/gen_a11y.mjs
import fs from 'node:fs';
import path from 'node:path';

const root = path.join(path.dirname(new URL(import.meta.url).pathname), '..');
const nm = path.join(root, 'oracle/node_modules');
const c = await import(path.join(nm, 'svelte/src/compiler/phases/2-analyze/visitors/shared/a11y/constants.js'));
const { roles, aria } = await import(path.join(nm, 'aria-query/lib/index.js')).then((m) => m.default ?? m);
const { AXObjectRoles, elementAXObjects } = await import(path.join(nm, 'axobject-query/lib/index.js')).then(
	(m) => m.default ?? m
);

const s = (x) => JSON.stringify(x);
const strs = (list) => `&[${list.map(s).join(', ')}]`;
const opt = (x) => (x === undefined ? 'None' : `Some(${s(String(x))})`);

let rs = '// Generated by tools/gen_a11y.mjs from aria-query and axobject-query. Do not edit.\n#![allow(clippy::all)]\n\n';
rs += 'pub struct Schema {\n\tpub name: &\'static str,\n\t/// `None` when the schema has no `attributes` array\n\tpub attributes: Option<&\'static [(&\'static str, Option<&\'static str>)]>,\n}\n\n';

const schema = (sc) =>
	`Schema { name: ${s(sc.name)}, attributes: ${
		sc.attributes ? `Some(&[${sc.attributes.map((a) => `(${s(a.name)}, ${opt(a.value)})`).join(', ')}])` : 'None'
	} }`;

for (const name of [
	'interactive_element_role_schemas',
	'non_interactive_element_role_schemas',
	'interactive_element_ax_object_schemas',
	'non_interactive_element_ax_object_schemas'
]) {
	rs += `pub static ${name.toUpperCase()}: &[Schema] = &[\n${c[name].map((sc) => '\t' + schema(sc) + ',\n').join('')}];\n\n`;
}

for (const name of ['aria_roles', 'abstract_roles', 'non_interactive_roles', 'interactive_roles']) {
	rs += `pub static ${name.toUpperCase()}: &[&str] = ${strs(c[name])};\n\n`;
}

// aria properties: name, type, values (in aria.keys() order)
rs += 'pub struct AriaProperty {\n\tpub name: &\'static str,\n\tpub r#type: &\'static str,\n\tpub values: &\'static [&\'static str],\n}\n\n';
rs += `pub static ARIA_PROPERTIES: &[AriaProperty] = &[\n${aria
	.keys()
	.map((k) => {
		const v = aria.get(k);
		return `\tAriaProperty { name: ${s(k)}, r#type: ${s(v.type)}, values: ${strs((v.values ?? []).map(String))} },\n`;
	})
	.join('')}];\n\n`;

// roles: name, required props, props
rs += 'pub struct Role {\n\tpub name: &\'static str,\n\tpub required_props: &\'static [&\'static str],\n\tpub props: &\'static [&\'static str],\n}\n\n';
rs += `pub static ROLES: &[Role] = &[\n${roles
	.keys()
	.map((k) => {
		const v = roles.get(k);
		return `\tRole { name: ${s(k)}, required_props: ${strs(Object.keys(v.requiredProps))}, props: ${strs(Object.keys(v.props))} },\n`;
	})
	.join('')}];\n\n`;

// elementAXObjects with the roles of their AX objects, for is_semantic_role_element
rs += 'pub struct ElementAxObject {\n\tpub schema: Schema,\n\tpub roles: &\'static [&\'static str],\n}\n\n';
rs += `pub static ELEMENT_AX_OBJECTS: &[ElementAxObject] = &[\n${[...elementAXObjects.entries()]
	.map(([sc, objects]) => {
		const role_names = [];
		for (const name of objects) {
			for (const r of AXObjectRoles.get(name) ?? []) role_names.push(r.name);
		}
		return `\tElementAxObject { schema: ${schema(sc)}, roles: ${strs(role_names)} },\n`;
	})
	.join('')}];\n`;

fs.writeFileSync(path.join(root, 'src/analyze/a11y_data.rs'), rs);
console.log('ok');
