// Generates src/errors.rs (every compile error) and src/analyze/warnings.rs (every compile
// warning) from Svelte's generated errors.js / warnings.js.
//   node tools/gen_messages.mjs <svelte/src/compiler>
import fs from 'node:fs';
import path from 'node:path';

const [compiler_dir] = process.argv.slice(2);
const root = path.join(path.dirname(new URL(import.meta.url).pathname), '..');

const ident = (p) => (p === 'type' ? 'r#type' : p);

/** Turn the body of a JS template literal into a Rust format string + args */
function convert(tpl) {
	let body = tpl.replace(/\\n/g, '\n').replace(/\\`/g, '`').replace(/\\\\/g, '\\');
	const args = [];
	body = body.replace(/[{}]/g, (c) => c + c).replace(/\$\{\{(\w+)\}\}/g, (_, n) => (args.push(n), '{}'));
	return { lit: JSON.stringify(body), args };
}

function parse(file, fn_name) {
	const src = fs.readFileSync(path.join(compiler_dir, file), 'utf-8') + '\n';
	const re = /export function (\w+)\(node(?:, )?([^)]*)\) \{\n([\s\S]*?)\n\}\n/g;
	const out = [];
	for (const m of src.matchAll(re)) {
		const body = m[3];
		const prefix = `\t${fn_name}(node, '${m[1]}', \``;
		if (!body.startsWith(prefix) || !body.endsWith('`);')) throw new Error('unexpected body for ' + m[1]);
		out.push({ code: m[1], params: m[2] ? m[2].split(', ') : [], tpl: body.slice(prefix.length, -3) });
	}
	return out;
}

/** Rust expression building the message */
function message(f) {
	const cond = /^\$\{(\w+)\n\t\t\? `((?:\\.|[^`\\])*)`\n\t\t: `((?:\\.|[^`\\])*)`\}(.*)$/s.exec(f.tpl);
	if (cond) {
		const [, param, yes, no, rest] = cond;
		const a = convert(yes + rest);
		const b = convert(no + rest);
		const fmt = (c, some) =>
			`format!(${c.lit}${c.args.map((x) => ', ' + (x === param && some ? 'v' : ident(x))).join('')})`;
		return {
			optional: param,
			expr: `match ${ident(param)} { Some(v) if !v.is_empty() => ${fmt(a, true)}, _ => ${fmt(b, false)} }`
		};
	}
	const c = convert(f.tpl);
	return { optional: null, expr: `format!(${c.lit}${c.args.map((x) => ', ' + ident(x)).join('')})` };
}

function params(f, optional) {
	return f.params.map((p) => `${ident(p.replace(/^\[|\]$/g, ''))}: ${p.replace(/^\[|\]$/g, '') === optional ? 'Option<&str>' : '&str'}`);
}

// errors
{
	const fns = parse('errors.js', 'e');
	let rs = '// Generated by tools/gen_messages.mjs from svelte/src/compiler/errors.js. Do not edit.\n#![allow(clippy::all)]\nuse crate::error::{CompileError, Loc};\n\n';
	for (const f of fns) {
		const m = message(f);
		const ps = params(f, m.optional);
		rs += `pub fn ${f.code}(node: impl Into<Loc>${ps.length ? ', ' + ps.join(', ') : ''}) -> CompileError {\n\tCompileError::new(node.into(), "${f.code}", ${m.expr})\n}\n\n`;
	}
	fs.writeFileSync(path.join(root, 'src/errors.rs'), rs);
	console.log(`${fns.length} errors`);
}

// warnings
{
	const fns = parse('warnings.js', 'w');
	let rs =
		'// Generated by tools/gen_messages.mjs from svelte/src/compiler/warnings.js. Do not edit.\n#![allow(clippy::all)]\n\n' +
		'/// A warning before it is attached to a position\npub struct W {\n\tpub code: &\'static str,\n\tpub message: String,\n}\n\n';
	for (const f of fns) {
		const m = message(f);
		const ps = params(f, m.optional);
		rs += `pub fn ${f.code}(${ps.join(', ')}) -> W {\n\tW { code: "${f.code}", message: ${m.expr} }\n}\n\n`;
	}
	fs.mkdirSync(path.join(root, 'src/analyze'), { recursive: true });
	fs.writeFileSync(path.join(root, 'src/analyze/warnings.rs'), rs);
	console.log(`${fns.length} warnings`);
}
