// Generated by tools/gen_messages.mjs from svelte/src/compiler/errors.js. Do not edit.
#![allow(clippy::all)]
use crate::error::{CompileError, Loc};

pub fn options_invalid_value(node: impl Into<Loc>, details: &str) -> CompileError {
	CompileError::new(node.into(), "options_invalid_value", format!("Invalid compiler option: {}\nhttps://svelte.dev/e/options_invalid_value", details))
}

pub fn options_removed(node: impl Into<Loc>, details: &str) -> CompileError {
	CompileError::new(node.into(), "options_removed", format!("Invalid compiler option: {}\nhttps://svelte.dev/e/options_removed", details))
}

pub fn options_unrecognised(node: impl Into<Loc>, keypath: &str) -> CompileError {
	CompileError::new(node.into(), "options_unrecognised", format!("Unrecognised compiler option {}\nhttps://svelte.dev/e/options_unrecognised", keypath))
}

pub fn bindable_invalid_location(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "bindable_invalid_location", format!("`$bindable()` can only be used inside a `$props()` declaration\nhttps://svelte.dev/e/bindable_invalid_location"))
}

pub fn constant_assignment(node: impl Into<Loc>, thing: &str) -> CompileError {
	CompileError::new(node.into(), "constant_assignment", format!("Cannot assign to {}\nhttps://svelte.dev/e/constant_assignment", thing))
}

pub fn constant_binding(node: impl Into<Loc>, thing: &str) -> CompileError {
	CompileError::new(node.into(), "constant_binding", format!("Cannot bind to {}\nhttps://svelte.dev/e/constant_binding", thing))
}

pub fn declaration_duplicate(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "declaration_duplicate", format!("`{}` has already been declared\nhttps://svelte.dev/e/declaration_duplicate", name))
}

pub fn declaration_duplicate_module_import(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "declaration_duplicate_module_import", format!("Cannot declare a variable with the same name as an import from `<script module>`\nhttps://svelte.dev/e/declaration_duplicate_module_import"))
}

pub fn derived_invalid_export(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "derived_invalid_export", format!("Cannot export derived state from a module. To expose the current derived value, export a function returning its value\nhttps://svelte.dev/e/derived_invalid_export"))
}

pub fn dollar_binding_invalid(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "dollar_binding_invalid", format!("The $ name is reserved, and cannot be used for variables and imports\nhttps://svelte.dev/e/dollar_binding_invalid"))
}

pub fn dollar_prefix_invalid(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "dollar_prefix_invalid", format!("The $ prefix is reserved, and cannot be used for variables and imports\nhttps://svelte.dev/e/dollar_prefix_invalid"))
}

pub fn duplicate_class_field(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "duplicate_class_field", format!("`{}` has already been declared\nhttps://svelte.dev/e/duplicate_class_field", name))
}

pub fn each_item_invalid_assignment(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "each_item_invalid_assignment", format!("Cannot reassign or bind to each block argument in runes mode. Use the array and index variables instead (e.g. `array[i] = value` instead of `entry = value`, or `bind:value={{array[i]}}` instead of `bind:value={{entry}}`)\nhttps://svelte.dev/e/each_item_invalid_assignment"))
}

pub fn effect_invalid_placement(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "effect_invalid_placement", format!("`$effect()` can only be used as an expression statement\nhttps://svelte.dev/e/effect_invalid_placement"))
}

pub fn experimental_async(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "experimental_async", format!("Cannot use `await` in deriveds and template expressions, or at the top level of a component, unless the `experimental.async` compiler option is `true`\nhttps://svelte.dev/e/experimental_async"))
}

pub fn export_undefined(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "export_undefined", format!("`{}` is not defined\nhttps://svelte.dev/e/export_undefined", name))
}

pub fn global_reference_invalid(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "global_reference_invalid", format!("`{}` is an illegal variable name. To reference a global variable called `{}`, use `globalThis.{}`\nhttps://svelte.dev/e/global_reference_invalid", name, name, name))
}

pub fn host_invalid_placement(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "host_invalid_placement", format!("`$host()` can only be used inside custom element component instances\nhttps://svelte.dev/e/host_invalid_placement"))
}

pub fn import_svelte_internal_forbidden(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "import_svelte_internal_forbidden", format!("Imports of `svelte/internal/*` are forbidden. It contains private runtime code which is subject to change without notice. If you're importing from `svelte/internal/*` to work around a limitation of Svelte, please open an issue at https://github.com/sveltejs/svelte and explain your use case\nhttps://svelte.dev/e/import_svelte_internal_forbidden"))
}

pub fn inspect_trace_generator(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "inspect_trace_generator", format!("`$inspect.trace(...)` cannot be used inside a generator function\nhttps://svelte.dev/e/inspect_trace_generator"))
}

pub fn inspect_trace_invalid_placement(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "inspect_trace_invalid_placement", format!("`$inspect.trace(...)` must be the first statement of a function body\nhttps://svelte.dev/e/inspect_trace_invalid_placement"))
}

pub fn invalid_arguments_usage(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "invalid_arguments_usage", format!("The arguments keyword cannot be used within the template or at the top level of a component\nhttps://svelte.dev/e/invalid_arguments_usage"))
}

pub fn legacy_await_invalid(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "legacy_await_invalid", format!("Cannot use `await` in deriveds and template expressions, or at the top level of a component, unless in runes mode\nhttps://svelte.dev/e/legacy_await_invalid"))
}

pub fn legacy_export_invalid(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "legacy_export_invalid", format!("Cannot use `export let` in runes mode — use `$props()` instead\nhttps://svelte.dev/e/legacy_export_invalid"))
}

pub fn legacy_props_invalid(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "legacy_props_invalid", format!("Cannot use `$$props` in runes mode\nhttps://svelte.dev/e/legacy_props_invalid"))
}

pub fn legacy_reactive_statement_invalid(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "legacy_reactive_statement_invalid", format!("`$:` is not allowed in runes mode, use `$derived` or `$effect` instead\nhttps://svelte.dev/e/legacy_reactive_statement_invalid"))
}

pub fn legacy_rest_props_invalid(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "legacy_rest_props_invalid", format!("Cannot use `$$restProps` in runes mode\nhttps://svelte.dev/e/legacy_rest_props_invalid"))
}

pub fn module_illegal_default_export(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "module_illegal_default_export", format!("A component cannot have a default export\nhttps://svelte.dev/e/module_illegal_default_export"))
}

pub fn props_duplicate(node: impl Into<Loc>, rune: &str) -> CompileError {
	CompileError::new(node.into(), "props_duplicate", format!("Cannot use `{}()` more than once\nhttps://svelte.dev/e/props_duplicate", rune))
}

pub fn props_id_invalid_placement(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "props_id_invalid_placement", format!("`$props.id()` can only be used at the top level of components as a variable declaration initializer\nhttps://svelte.dev/e/props_id_invalid_placement"))
}

pub fn props_illegal_name(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "props_illegal_name", format!("Declaring or accessing a prop starting with `$$` is illegal (they are reserved for Svelte internals)\nhttps://svelte.dev/e/props_illegal_name"))
}

pub fn props_invalid_identifier(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "props_invalid_identifier", format!("`$props()` can only be used with an object destructuring pattern\nhttps://svelte.dev/e/props_invalid_identifier"))
}

pub fn props_invalid_pattern(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "props_invalid_pattern", format!("`$props()` assignment must not contain nested properties or computed keys\nhttps://svelte.dev/e/props_invalid_pattern"))
}

pub fn props_invalid_placement(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "props_invalid_placement", format!("`$props()` can only be used at the top level of components as a variable declaration initializer\nhttps://svelte.dev/e/props_invalid_placement"))
}

pub fn reactive_declaration_cycle(node: impl Into<Loc>, cycle: &str) -> CompileError {
	CompileError::new(node.into(), "reactive_declaration_cycle", format!("Cyclical dependency detected: {}\nhttps://svelte.dev/e/reactive_declaration_cycle", cycle))
}

pub fn rune_invalid_arguments(node: impl Into<Loc>, rune: &str) -> CompileError {
	CompileError::new(node.into(), "rune_invalid_arguments", format!("`{}` cannot be called with arguments\nhttps://svelte.dev/e/rune_invalid_arguments", rune))
}

pub fn rune_invalid_arguments_length(node: impl Into<Loc>, rune: &str, args: &str) -> CompileError {
	CompileError::new(node.into(), "rune_invalid_arguments_length", format!("`{}` must be called with {}\nhttps://svelte.dev/e/rune_invalid_arguments_length", rune, args))
}

pub fn rune_invalid_computed_property(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "rune_invalid_computed_property", format!("Cannot access a computed property of a rune\nhttps://svelte.dev/e/rune_invalid_computed_property"))
}

pub fn rune_invalid_name(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "rune_invalid_name", format!("`{}` is not a valid rune\nhttps://svelte.dev/e/rune_invalid_name", name))
}

pub fn rune_invalid_spread(node: impl Into<Loc>, rune: &str) -> CompileError {
	CompileError::new(node.into(), "rune_invalid_spread", format!("`{}` cannot be called with a spread argument\nhttps://svelte.dev/e/rune_invalid_spread", rune))
}

pub fn rune_invalid_usage(node: impl Into<Loc>, rune: &str) -> CompileError {
	CompileError::new(node.into(), "rune_invalid_usage", format!("Cannot use `{}` rune in non-runes mode\nhttps://svelte.dev/e/rune_invalid_usage", rune))
}

pub fn rune_missing_parentheses(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "rune_missing_parentheses", format!("Cannot use rune without parentheses\nhttps://svelte.dev/e/rune_missing_parentheses"))
}

pub fn rune_removed(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "rune_removed", format!("The `{}` rune has been removed\nhttps://svelte.dev/e/rune_removed", name))
}

pub fn rune_renamed(node: impl Into<Loc>, name: &str, replacement: &str) -> CompileError {
	CompileError::new(node.into(), "rune_renamed", format!("`{}` is now `{}`\nhttps://svelte.dev/e/rune_renamed", name, replacement))
}

pub fn runes_mode_invalid_import(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "runes_mode_invalid_import", format!("{} cannot be used in runes mode\nhttps://svelte.dev/e/runes_mode_invalid_import", name))
}

pub fn snippet_invalid_export(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "snippet_invalid_export", format!("An exported snippet can only reference things declared in a `<script module>`, or other exportable snippets\nhttps://svelte.dev/e/snippet_invalid_export"))
}

pub fn snippet_parameter_assignment(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "snippet_parameter_assignment", format!("Cannot reassign or bind to snippet parameter\nhttps://svelte.dev/e/snippet_parameter_assignment"))
}

pub fn state_field_duplicate(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "state_field_duplicate", format!("`{}` has already been declared on this class\nhttps://svelte.dev/e/state_field_duplicate", name))
}

pub fn state_field_invalid_assignment(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "state_field_invalid_assignment", format!("Cannot assign to a state field before its declaration\nhttps://svelte.dev/e/state_field_invalid_assignment"))
}

pub fn state_invalid_export(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "state_invalid_export", format!("Cannot export state from a module if it is reassigned. Either export a function returning the state value or only mutate the state value's properties\nhttps://svelte.dev/e/state_invalid_export"))
}

pub fn state_invalid_placement(node: impl Into<Loc>, rune: &str) -> CompileError {
	CompileError::new(node.into(), "state_invalid_placement", format!("`{}(...)` can only be used as a variable declaration initializer, a class field declaration, or the first assignment to a class field at the top level of the constructor.\nhttps://svelte.dev/e/state_invalid_placement", rune))
}

pub fn store_invalid_scoped_subscription(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "store_invalid_scoped_subscription", format!("Cannot subscribe to stores that are not declared at the top level of the component\nhttps://svelte.dev/e/store_invalid_scoped_subscription"))
}

pub fn store_invalid_subscription(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "store_invalid_subscription", format!("Cannot reference store value inside `<script module>`\nhttps://svelte.dev/e/store_invalid_subscription"))
}

pub fn store_invalid_subscription_module(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "store_invalid_subscription_module", format!("Cannot reference store value outside a `.svelte` file\nhttps://svelte.dev/e/store_invalid_subscription_module"))
}

pub fn typescript_invalid_feature(node: impl Into<Loc>, feature: &str) -> CompileError {
	CompileError::new(node.into(), "typescript_invalid_feature", format!("TypeScript language features like {} are not natively supported, and their use is generally discouraged. Outside of `<script>` tags, these features are not supported. For use within `<script>` tags, you will need to use a preprocessor to convert it to JavaScript before it gets passed to the Svelte compiler. If you are using `vitePreprocess`, make sure to specifically enable preprocessing script tags (`vitePreprocess({{ script: true }})`)\nhttps://svelte.dev/e/typescript_invalid_feature", feature))
}

pub fn css_empty_declaration(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "css_empty_declaration", format!("Declaration cannot be empty\nhttps://svelte.dev/e/css_empty_declaration"))
}

pub fn css_expected_identifier(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "css_expected_identifier", format!("Expected a valid CSS identifier\nhttps://svelte.dev/e/css_expected_identifier"))
}

pub fn css_global_block_invalid_combinator(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "css_global_block_invalid_combinator", format!("A `:global` selector cannot follow a `{}` combinator\nhttps://svelte.dev/e/css_global_block_invalid_combinator", name))
}

pub fn css_global_block_invalid_declaration(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "css_global_block_invalid_declaration", format!("A top-level `:global {{...}}` block can only contain rules, not declarations\nhttps://svelte.dev/e/css_global_block_invalid_declaration"))
}

pub fn css_global_block_invalid_list(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "css_global_block_invalid_list", format!("A `:global` selector cannot be part of a selector list with entries that don't contain `:global`\nhttps://svelte.dev/e/css_global_block_invalid_list"))
}

pub fn css_global_block_invalid_modifier(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "css_global_block_invalid_modifier", format!("A `:global` selector cannot modify an existing selector\nhttps://svelte.dev/e/css_global_block_invalid_modifier"))
}

pub fn css_global_block_invalid_modifier_start(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "css_global_block_invalid_modifier_start", format!("A `:global` selector can only be modified if it is a descendant of other selectors\nhttps://svelte.dev/e/css_global_block_invalid_modifier_start"))
}

pub fn css_global_block_invalid_placement(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "css_global_block_invalid_placement", format!("A `:global` selector cannot be inside a pseudoclass\nhttps://svelte.dev/e/css_global_block_invalid_placement"))
}

pub fn css_global_invalid_placement(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "css_global_invalid_placement", format!("`:global(...)` can be at the start or end of a selector sequence, but not in the middle\nhttps://svelte.dev/e/css_global_invalid_placement"))
}

pub fn css_global_invalid_selector(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "css_global_invalid_selector", format!("`:global(...)` must contain exactly one selector\nhttps://svelte.dev/e/css_global_invalid_selector"))
}

pub fn css_global_invalid_selector_list(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "css_global_invalid_selector_list", format!("`:global(...)` must not contain type or universal selectors when used in a compound selector\nhttps://svelte.dev/e/css_global_invalid_selector_list"))
}

pub fn css_nesting_selector_invalid_placement(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "css_nesting_selector_invalid_placement", format!("Nesting selectors can only be used inside a rule or as the first selector inside a lone `:global(...)`\nhttps://svelte.dev/e/css_nesting_selector_invalid_placement"))
}

pub fn css_selector_invalid(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "css_selector_invalid", format!("Invalid selector\nhttps://svelte.dev/e/css_selector_invalid"))
}

pub fn css_type_selector_invalid_placement(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "css_type_selector_invalid_placement", format!("`:global(...)` must not be followed by a type selector\nhttps://svelte.dev/e/css_type_selector_invalid_placement"))
}

pub fn animation_duplicate(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "animation_duplicate", format!("An element can only have one 'animate' directive\nhttps://svelte.dev/e/animation_duplicate"))
}

pub fn animation_invalid_placement(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "animation_invalid_placement", format!("An element that uses the `animate:` directive must be the only child of a keyed `{{#each ...}}` block\nhttps://svelte.dev/e/animation_invalid_placement"))
}

pub fn animation_missing_key(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "animation_missing_key", format!("An element that uses the `animate:` directive must be the only child of a keyed `{{#each ...}}` block. Did you forget to add a key to your each block?\nhttps://svelte.dev/e/animation_missing_key"))
}

pub fn attribute_contenteditable_dynamic(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "attribute_contenteditable_dynamic", format!("'contenteditable' attribute cannot be dynamic if element uses two-way binding\nhttps://svelte.dev/e/attribute_contenteditable_dynamic"))
}

pub fn attribute_contenteditable_missing(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "attribute_contenteditable_missing", format!("'contenteditable' attribute is required for textContent, innerHTML and innerText two-way bindings\nhttps://svelte.dev/e/attribute_contenteditable_missing"))
}

pub fn attribute_duplicate(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "attribute_duplicate", format!("Attributes need to be unique\nhttps://svelte.dev/e/attribute_duplicate"))
}

pub fn attribute_empty_shorthand(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "attribute_empty_shorthand", format!("Attribute shorthand cannot be empty\nhttps://svelte.dev/e/attribute_empty_shorthand"))
}

pub fn attribute_invalid_event_handler(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "attribute_invalid_event_handler", format!("Event attribute must be a JavaScript expression, not a string\nhttps://svelte.dev/e/attribute_invalid_event_handler"))
}

pub fn attribute_invalid_multiple(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "attribute_invalid_multiple", format!("'multiple' attribute must be static if select uses two-way binding\nhttps://svelte.dev/e/attribute_invalid_multiple"))
}

pub fn attribute_invalid_name(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "attribute_invalid_name", format!("'{}' is not a valid attribute name\nhttps://svelte.dev/e/attribute_invalid_name", name))
}

pub fn attribute_invalid_sequence_expression(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "attribute_invalid_sequence_expression", format!("Comma-separated expressions are not allowed as attribute/directive values in runes mode, unless wrapped in parentheses\nhttps://svelte.dev/e/attribute_invalid_sequence_expression"))
}

pub fn attribute_invalid_type(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "attribute_invalid_type", format!("'type' attribute must be a static text value if input uses two-way binding\nhttps://svelte.dev/e/attribute_invalid_type"))
}

pub fn attribute_unquoted_sequence(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "attribute_unquoted_sequence", format!("Attribute values containing `{{...}}` must be enclosed in quote marks, unless the value only contains the expression\nhttps://svelte.dev/e/attribute_unquoted_sequence"))
}

pub fn bind_group_invalid_expression(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "bind_group_invalid_expression", format!("`bind:group` can only bind to an Identifier or MemberExpression\nhttps://svelte.dev/e/bind_group_invalid_expression"))
}

pub fn bind_group_invalid_snippet_parameter(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "bind_group_invalid_snippet_parameter", format!("Cannot `bind:group` to a snippet parameter\nhttps://svelte.dev/e/bind_group_invalid_snippet_parameter"))
}

pub fn bind_invalid_expression(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "bind_invalid_expression", format!("Can only bind to an Identifier or MemberExpression or a `{{get, set}}` pair\nhttps://svelte.dev/e/bind_invalid_expression"))
}

pub fn bind_invalid_name(node: impl Into<Loc>, name: &str, explanation: Option<&str>) -> CompileError {
	CompileError::new(node.into(), "bind_invalid_name", match explanation { Some(v) if !v.is_empty() => format!("`bind:{}` is not a valid binding. {}\nhttps://svelte.dev/e/bind_invalid_name", name, v), _ => format!("`bind:{}` is not a valid binding\nhttps://svelte.dev/e/bind_invalid_name", name) })
}

pub fn bind_invalid_parens(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "bind_invalid_parens", format!("`bind:{}={{get, set}}` must not have surrounding parentheses\nhttps://svelte.dev/e/bind_invalid_parens", name))
}

pub fn bind_invalid_target(node: impl Into<Loc>, name: &str, elements: &str) -> CompileError {
	CompileError::new(node.into(), "bind_invalid_target", format!("`bind:{}` can only be used with {}\nhttps://svelte.dev/e/bind_invalid_target", name, elements))
}

pub fn bind_invalid_value(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "bind_invalid_value", format!("Can only bind to state or props\nhttps://svelte.dev/e/bind_invalid_value"))
}

pub fn block_duplicate_clause(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "block_duplicate_clause", format!("{} cannot appear more than once within a block\nhttps://svelte.dev/e/block_duplicate_clause", name))
}

pub fn block_invalid_continuation_placement(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "block_invalid_continuation_placement", format!("{{:...}} block is invalid at this position (did you forget to close the preceding element or block?)\nhttps://svelte.dev/e/block_invalid_continuation_placement"))
}

pub fn block_invalid_elseif(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "block_invalid_elseif", format!("'elseif' should be 'else if'\nhttps://svelte.dev/e/block_invalid_elseif"))
}

pub fn block_invalid_placement(node: impl Into<Loc>, name: &str, location: &str) -> CompileError {
	CompileError::new(node.into(), "block_invalid_placement", format!("{{#{} ...}} block cannot be {}\nhttps://svelte.dev/e/block_invalid_placement", name, location))
}

pub fn block_unclosed(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "block_unclosed", format!("Block was left open\nhttps://svelte.dev/e/block_unclosed"))
}

pub fn block_unexpected_character(node: impl Into<Loc>, character: &str) -> CompileError {
	CompileError::new(node.into(), "block_unexpected_character", format!("Expected a `{}` character immediately following the opening bracket\nhttps://svelte.dev/e/block_unexpected_character", character))
}

pub fn block_unexpected_close(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "block_unexpected_close", format!("Unexpected block closing tag\nhttps://svelte.dev/e/block_unexpected_close"))
}

pub fn component_invalid_directive(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "component_invalid_directive", format!("This type of directive is not valid on components\nhttps://svelte.dev/e/component_invalid_directive"))
}

pub fn const_tag_cycle(node: impl Into<Loc>, cycle: &str) -> CompileError {
	CompileError::new(node.into(), "const_tag_cycle", format!("Cyclical dependency detected: {}\nhttps://svelte.dev/e/const_tag_cycle", cycle))
}

pub fn const_tag_invalid_expression(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "const_tag_invalid_expression", format!("{{@const ...}} must consist of a single variable declaration\nhttps://svelte.dev/e/const_tag_invalid_expression"))
}

pub fn const_tag_invalid_placement(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "const_tag_invalid_placement", format!("`{{@const}}` must be the immediate child of `{{#snippet}}`, `{{#if}}`, `{{:else if}}`, `{{:else}}`, `{{#each}}`, `{{:then}}`, `{{:catch}}`, `<svelte:fragment>`, `<svelte:boundary>` or `<Component>`\nhttps://svelte.dev/e/const_tag_invalid_placement"))
}

pub fn const_tag_invalid_reference(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "const_tag_invalid_reference", format!("The `{{@const {} = ...}}` declaration is not available in this snippet\nhttps://svelte.dev/e/const_tag_invalid_reference", name))
}

pub fn debug_tag_invalid_arguments(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "debug_tag_invalid_arguments", format!("{{@debug ...}} arguments must be identifiers, not arbitrary expressions\nhttps://svelte.dev/e/debug_tag_invalid_arguments"))
}

pub fn declaration_tag_invalid_type(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "declaration_tag_invalid_type", format!("Declaration tags must be `let` or `const` declarations\nhttps://svelte.dev/e/declaration_tag_invalid_type"))
}

pub fn declaration_tag_no_legacy_mode(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "declaration_tag_no_legacy_mode", format!("Declaration tags cannot be used in legacy mode\nhttps://svelte.dev/e/declaration_tag_no_legacy_mode"))
}

pub fn directive_invalid_value(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "directive_invalid_value", format!("Directive value must be a JavaScript expression enclosed in curly braces\nhttps://svelte.dev/e/directive_invalid_value"))
}

pub fn directive_missing_name(node: impl Into<Loc>, r#type: &str) -> CompileError {
	CompileError::new(node.into(), "directive_missing_name", format!("`{}` name cannot be empty\nhttps://svelte.dev/e/directive_missing_name", r#type))
}

pub fn each_key_without_as(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "each_key_without_as", format!("An `{{#each ...}}` block without an `as` clause cannot have a key\nhttps://svelte.dev/e/each_key_without_as"))
}

pub fn element_invalid_closing_tag(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "element_invalid_closing_tag", format!("`</{}>` attempted to close an element that was not open\nhttps://svelte.dev/e/element_invalid_closing_tag", name))
}

pub fn element_invalid_closing_tag_autoclosed(node: impl Into<Loc>, name: &str, reason: &str) -> CompileError {
	CompileError::new(node.into(), "element_invalid_closing_tag_autoclosed", format!("`</{}>` attempted to close element that was already automatically closed by `<{}>` (cannot nest `<{}>` inside `<{}>`)\nhttps://svelte.dev/e/element_invalid_closing_tag_autoclosed", name, reason, reason, name))
}

pub fn element_unclosed(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "element_unclosed", format!("`<{}>` was left open\nhttps://svelte.dev/e/element_unclosed", name))
}

pub fn event_handler_invalid_component_modifier(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "event_handler_invalid_component_modifier", format!("Event modifiers other than 'once' can only be used on DOM elements\nhttps://svelte.dev/e/event_handler_invalid_component_modifier"))
}

pub fn event_handler_invalid_modifier(node: impl Into<Loc>, list: &str) -> CompileError {
	CompileError::new(node.into(), "event_handler_invalid_modifier", format!("Valid event modifiers are {}\nhttps://svelte.dev/e/event_handler_invalid_modifier", list))
}

pub fn event_handler_invalid_modifier_combination(node: impl Into<Loc>, modifier1: &str, modifier2: &str) -> CompileError {
	CompileError::new(node.into(), "event_handler_invalid_modifier_combination", format!("The '{}' and '{}' modifiers cannot be used together\nhttps://svelte.dev/e/event_handler_invalid_modifier_combination", modifier1, modifier2))
}

pub fn expected_attribute_value(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "expected_attribute_value", format!("Expected attribute value\nhttps://svelte.dev/e/expected_attribute_value"))
}

pub fn expected_block_type(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "expected_block_type", format!("Expected 'if', 'each', 'await', 'key' or 'snippet'\nhttps://svelte.dev/e/expected_block_type"))
}

pub fn expected_identifier(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "expected_identifier", format!("Expected an identifier\nhttps://svelte.dev/e/expected_identifier"))
}

pub fn expected_pattern(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "expected_pattern", format!("Expected identifier or destructure pattern\nhttps://svelte.dev/e/expected_pattern"))
}

pub fn expected_tag(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "expected_tag", format!("Expected 'html', 'render', 'attach', 'const', or 'debug'\nhttps://svelte.dev/e/expected_tag"))
}

pub fn expected_token(node: impl Into<Loc>, token: &str) -> CompileError {
	CompileError::new(node.into(), "expected_token", format!("Expected token {}\nhttps://svelte.dev/e/expected_token", token))
}

pub fn expected_whitespace(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "expected_whitespace", format!("Expected whitespace\nhttps://svelte.dev/e/expected_whitespace"))
}

pub fn illegal_await_expression(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "illegal_await_expression", format!("`use:`, `transition:` and `animate:` directives, attachments and bindings do not support await expressions\nhttps://svelte.dev/e/illegal_await_expression"))
}

pub fn illegal_element_attribute(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "illegal_element_attribute", format!("`<{}>` does not support non-event attributes or spread attributes\nhttps://svelte.dev/e/illegal_element_attribute", name))
}

pub fn js_parse_error(node: impl Into<Loc>, message: &str) -> CompileError {
	CompileError::new(node.into(), "js_parse_error", format!("{}\nhttps://svelte.dev/e/js_parse_error", message))
}

pub fn let_directive_invalid_placement(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "let_directive_invalid_placement", format!("`let:` directive at invalid position\nhttps://svelte.dev/e/let_directive_invalid_placement"))
}

pub fn let_directive_snippet_conflict(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "let_directive_snippet_conflict", format!("Cannot use `let:` directives on a component that has a `children` snippet. Use snippet parameters instead (e.g. `{{#snippet children({{ {} }})}}`)\nhttps://svelte.dev/e/let_directive_snippet_conflict", name))
}

pub fn mixed_event_handler_syntaxes(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "mixed_event_handler_syntaxes", format!("Mixing old (on:{}) and new syntaxes for event handling is not allowed. Use only the on{} syntax\nhttps://svelte.dev/e/mixed_event_handler_syntaxes", name, name))
}

pub fn node_invalid_placement(node: impl Into<Loc>, message: &str) -> CompileError {
	CompileError::new(node.into(), "node_invalid_placement", format!("{}. The browser will 'repair' the HTML (by moving, removing, or inserting elements) which breaks Svelte's assumptions about the structure of your components.\nhttps://svelte.dev/e/node_invalid_placement", message))
}

pub fn render_tag_invalid_call_expression(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "render_tag_invalid_call_expression", format!("Calling a snippet function using apply, bind or call is not allowed\nhttps://svelte.dev/e/render_tag_invalid_call_expression"))
}

pub fn render_tag_invalid_expression(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "render_tag_invalid_expression", format!("`{{@render ...}}` tags can only contain call expressions\nhttps://svelte.dev/e/render_tag_invalid_expression"))
}

pub fn render_tag_invalid_spread_argument(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "render_tag_invalid_spread_argument", format!("cannot use spread arguments in `{{@render ...}}` tags\nhttps://svelte.dev/e/render_tag_invalid_spread_argument"))
}

pub fn script_duplicate(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "script_duplicate", format!("A component can have a single top-level `<script>` element and/or a single top-level `<script module>` element\nhttps://svelte.dev/e/script_duplicate"))
}

pub fn script_invalid_attribute_value(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "script_invalid_attribute_value", format!("If the `{}` attribute is supplied, it must be a boolean attribute\nhttps://svelte.dev/e/script_invalid_attribute_value", name))
}

pub fn script_invalid_context(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "script_invalid_context", format!("If the context attribute is supplied, its value must be \"module\"\nhttps://svelte.dev/e/script_invalid_context"))
}

pub fn script_reserved_attribute(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "script_reserved_attribute", format!("The `{}` attribute is reserved and cannot be used\nhttps://svelte.dev/e/script_reserved_attribute", name))
}

pub fn slot_attribute_duplicate(node: impl Into<Loc>, name: &str, component: &str) -> CompileError {
	CompileError::new(node.into(), "slot_attribute_duplicate", format!("Duplicate slot name '{}' in <{}>\nhttps://svelte.dev/e/slot_attribute_duplicate", name, component))
}

pub fn slot_attribute_invalid(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "slot_attribute_invalid", format!("slot attribute must be a static value\nhttps://svelte.dev/e/slot_attribute_invalid"))
}

pub fn slot_attribute_invalid_placement(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "slot_attribute_invalid_placement", format!("Element with a slot='...' attribute must be a child of a component or a descendant of a custom element\nhttps://svelte.dev/e/slot_attribute_invalid_placement"))
}

pub fn slot_default_duplicate(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "slot_default_duplicate", format!("Found default slot content alongside an explicit slot=\"default\"\nhttps://svelte.dev/e/slot_default_duplicate"))
}

pub fn slot_element_invalid_attribute(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "slot_element_invalid_attribute", format!("`<slot>` can only receive attributes and (optionally) let directives\nhttps://svelte.dev/e/slot_element_invalid_attribute"))
}

pub fn slot_element_invalid_name(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "slot_element_invalid_name", format!("slot attribute must be a static value\nhttps://svelte.dev/e/slot_element_invalid_name"))
}

pub fn slot_element_invalid_name_default(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "slot_element_invalid_name_default", format!("`default` is a reserved word — it cannot be used as a slot name\nhttps://svelte.dev/e/slot_element_invalid_name_default"))
}

pub fn slot_snippet_conflict(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "slot_snippet_conflict", format!("Cannot use `<slot>` syntax and `{{@render ...}}` tags in the same component. Migrate towards `{{@render ...}}` tags completely\nhttps://svelte.dev/e/slot_snippet_conflict"))
}

pub fn snippet_conflict(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "snippet_conflict", format!("Cannot use explicit children snippet at the same time as implicit children content. Remove either the non-whitespace content or the children snippet block\nhttps://svelte.dev/e/snippet_conflict"))
}

pub fn snippet_invalid_rest_parameter(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "snippet_invalid_rest_parameter", format!("Snippets do not support rest parameters; use an array instead\nhttps://svelte.dev/e/snippet_invalid_rest_parameter"))
}

pub fn snippet_shadowing_prop(node: impl Into<Loc>, prop: &str) -> CompileError {
	CompileError::new(node.into(), "snippet_shadowing_prop", format!("This snippet is shadowing the prop `{}` with the same name\nhttps://svelte.dev/e/snippet_shadowing_prop", prop))
}

pub fn style_directive_invalid_modifier(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "style_directive_invalid_modifier", format!("`style:` directive can only use the `important` modifier\nhttps://svelte.dev/e/style_directive_invalid_modifier"))
}

pub fn style_duplicate(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "style_duplicate", format!("A component can have a single top-level `<style>` element\nhttps://svelte.dev/e/style_duplicate"))
}

pub fn svelte_body_illegal_attribute(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "svelte_body_illegal_attribute", format!("`<svelte:body>` does not support non-event attributes or spread attributes\nhttps://svelte.dev/e/svelte_body_illegal_attribute"))
}

pub fn svelte_boundary_invalid_attribute(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "svelte_boundary_invalid_attribute", format!("Valid attributes on `<svelte:boundary>` are `onerror` and `failed`\nhttps://svelte.dev/e/svelte_boundary_invalid_attribute"))
}

pub fn svelte_boundary_invalid_attribute_value(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "svelte_boundary_invalid_attribute_value", format!("Attribute value must be a non-string expression\nhttps://svelte.dev/e/svelte_boundary_invalid_attribute_value"))
}

pub fn svelte_component_invalid_this(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "svelte_component_invalid_this", format!("Invalid component definition — must be an `{{expression}}`\nhttps://svelte.dev/e/svelte_component_invalid_this"))
}

pub fn svelte_component_missing_this(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "svelte_component_missing_this", format!("`<svelte:component>` must have a 'this' attribute\nhttps://svelte.dev/e/svelte_component_missing_this"))
}

pub fn svelte_element_missing_this(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "svelte_element_missing_this", format!("`<svelte:element>` must have a 'this' attribute with a value\nhttps://svelte.dev/e/svelte_element_missing_this"))
}

pub fn svelte_fragment_invalid_attribute(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "svelte_fragment_invalid_attribute", format!("`<svelte:fragment>` can only have a slot attribute and (optionally) a let: directive\nhttps://svelte.dev/e/svelte_fragment_invalid_attribute"))
}

pub fn svelte_fragment_invalid_placement(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "svelte_fragment_invalid_placement", format!("`<svelte:fragment>` must be the direct child of a component\nhttps://svelte.dev/e/svelte_fragment_invalid_placement"))
}

pub fn svelte_head_illegal_attribute(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "svelte_head_illegal_attribute", format!("`<svelte:head>` cannot have attributes nor directives\nhttps://svelte.dev/e/svelte_head_illegal_attribute"))
}

pub fn svelte_meta_duplicate(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "svelte_meta_duplicate", format!("A component can only have one `<{}>` element\nhttps://svelte.dev/e/svelte_meta_duplicate", name))
}

pub fn svelte_meta_invalid_content(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "svelte_meta_invalid_content", format!("<{}> cannot have children\nhttps://svelte.dev/e/svelte_meta_invalid_content", name))
}

pub fn svelte_meta_invalid_placement(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "svelte_meta_invalid_placement", format!("`<{}>` tags cannot be inside elements or blocks\nhttps://svelte.dev/e/svelte_meta_invalid_placement", name))
}

pub fn svelte_meta_invalid_tag(node: impl Into<Loc>, list: &str) -> CompileError {
	CompileError::new(node.into(), "svelte_meta_invalid_tag", format!("Valid `<svelte:...>` tag names are {}\nhttps://svelte.dev/e/svelte_meta_invalid_tag", list))
}

pub fn svelte_options_deprecated_tag(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "svelte_options_deprecated_tag", format!("\"tag\" option is deprecated — use \"customElement\" instead\nhttps://svelte.dev/e/svelte_options_deprecated_tag"))
}

pub fn svelte_options_invalid_attribute(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "svelte_options_invalid_attribute", format!("`<svelte:options>` can only receive static attributes\nhttps://svelte.dev/e/svelte_options_invalid_attribute"))
}

pub fn svelte_options_invalid_attribute_value(node: impl Into<Loc>, list: &str) -> CompileError {
	CompileError::new(node.into(), "svelte_options_invalid_attribute_value", format!("Value must be {}, if specified\nhttps://svelte.dev/e/svelte_options_invalid_attribute_value", list))
}

pub fn svelte_options_invalid_customelement(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "svelte_options_invalid_customelement", format!("\"customElement\" must be a string literal defining a valid custom element name or an object of the form {{ tag?: string; shadow?: \"open\" | \"none\" | `ShadowRootInit`; props?: {{ [key: string]: {{ attribute?: string; reflect?: boolean; type: .. }} }} }}\nhttps://svelte.dev/e/svelte_options_invalid_customelement"))
}

pub fn svelte_options_invalid_customelement_props(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "svelte_options_invalid_customelement_props", format!("\"props\" must be a statically analyzable object literal of the form \"{{ [key: string]: {{ attribute?: string; reflect?: boolean; type?: \"String\" | \"Boolean\" | \"Number\" | \"Array\" | \"Object\" }}\"\nhttps://svelte.dev/e/svelte_options_invalid_customelement_props"))
}

pub fn svelte_options_invalid_customelement_shadow(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "svelte_options_invalid_customelement_shadow", format!("\"shadow\" must be either \"open\", \"none\" or `ShadowRootInit` object.\nhttps://svelte.dev/e/svelte_options_invalid_customelement_shadow"))
}

pub fn svelte_options_invalid_tagname(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "svelte_options_invalid_tagname", format!("Tag name must be lowercase and hyphenated\nhttps://svelte.dev/e/svelte_options_invalid_tagname"))
}

pub fn svelte_options_reserved_tagname(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "svelte_options_reserved_tagname", format!("Tag name is reserved\nhttps://svelte.dev/e/svelte_options_reserved_tagname"))
}

pub fn svelte_options_unknown_attribute(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "svelte_options_unknown_attribute", format!("`<svelte:options>` unknown attribute '{}'\nhttps://svelte.dev/e/svelte_options_unknown_attribute", name))
}

pub fn svelte_self_invalid_placement(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "svelte_self_invalid_placement", format!("`<svelte:self>` components can only exist inside `{{#if}}` blocks, `{{#each}}` blocks, `{{#snippet}}` blocks or slots passed to components\nhttps://svelte.dev/e/svelte_self_invalid_placement"))
}

pub fn tag_invalid_name(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "tag_invalid_name", format!("Expected a valid element or component name. Components must have a valid variable name or dot notation expression\nhttps://svelte.dev/e/tag_invalid_name"))
}

pub fn tag_invalid_placement(node: impl Into<Loc>, name: &str, location: &str) -> CompileError {
	CompileError::new(node.into(), "tag_invalid_placement", format!("{{@{} ...}} tag cannot be {}\nhttps://svelte.dev/e/tag_invalid_placement", name, location))
}

pub fn textarea_invalid_content(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "textarea_invalid_content", format!("A `<textarea>` can have either a value attribute or (equivalently) child content, but not both\nhttps://svelte.dev/e/textarea_invalid_content"))
}

pub fn title_illegal_attribute(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "title_illegal_attribute", format!("`<title>` cannot have attributes nor directives\nhttps://svelte.dev/e/title_illegal_attribute"))
}

pub fn title_invalid_content(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "title_invalid_content", format!("`<title>` can only contain text and {{tags}}\nhttps://svelte.dev/e/title_invalid_content"))
}

pub fn transition_conflict(node: impl Into<Loc>, r#type: &str, existing: &str) -> CompileError {
	CompileError::new(node.into(), "transition_conflict", format!("Cannot use `{}:` alongside existing `{}:` directive\nhttps://svelte.dev/e/transition_conflict", r#type, existing))
}

pub fn transition_duplicate(node: impl Into<Loc>, r#type: &str) -> CompileError {
	CompileError::new(node.into(), "transition_duplicate", format!("Cannot use multiple `{}:` directives on a single element\nhttps://svelte.dev/e/transition_duplicate", r#type))
}

pub fn unexpected_eof(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "unexpected_eof", format!("Unexpected end of input\nhttps://svelte.dev/e/unexpected_eof"))
}

pub fn unexpected_reserved_word(node: impl Into<Loc>, word: &str) -> CompileError {
	CompileError::new(node.into(), "unexpected_reserved_word", format!("'{}' is a reserved word in JavaScript and cannot be used here\nhttps://svelte.dev/e/unexpected_reserved_word", word))
}

pub fn unterminated_string_constant(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "unterminated_string_constant", format!("Unterminated string constant\nhttps://svelte.dev/e/unterminated_string_constant"))
}

pub fn void_element_invalid_content(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "void_element_invalid_content", format!("Void elements cannot have children or closing tags\nhttps://svelte.dev/e/void_element_invalid_content"))
}

