// Generated by tools/gen_errors.mjs from svelte/src/compiler/errors.js. Do not edit.
#![allow(clippy::all)]
use crate::error::{CompileError, Loc};

pub fn attribute_duplicate(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "attribute_duplicate", format!("Attributes need to be unique\nhttps://svelte.dev/e/attribute_duplicate"))
}

pub fn attribute_empty_shorthand(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "attribute_empty_shorthand", format!("Attribute shorthand cannot be empty\nhttps://svelte.dev/e/attribute_empty_shorthand"))
}

pub fn block_duplicate_clause(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "block_duplicate_clause", format!("{} cannot appear more than once within a block\nhttps://svelte.dev/e/block_duplicate_clause", name))
}

pub fn block_invalid_continuation_placement(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "block_invalid_continuation_placement", format!("{{:...}} block is invalid at this position (did you forget to close the preceding element or block?)\nhttps://svelte.dev/e/block_invalid_continuation_placement"))
}

pub fn block_invalid_elseif(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "block_invalid_elseif", format!("'elseif' should be 'else if'\nhttps://svelte.dev/e/block_invalid_elseif"))
}

pub fn block_invalid_placement(node: impl Into<Loc>, name: &str, location: &str) -> CompileError {
	CompileError::new(node.into(), "block_invalid_placement", format!("{{#{} ...}} block cannot be {}\nhttps://svelte.dev/e/block_invalid_placement", name, location))
}

pub fn block_unclosed(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "block_unclosed", format!("Block was left open\nhttps://svelte.dev/e/block_unclosed"))
}

pub fn block_unexpected_close(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "block_unexpected_close", format!("Unexpected block closing tag\nhttps://svelte.dev/e/block_unexpected_close"))
}

pub fn const_tag_invalid_expression(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "const_tag_invalid_expression", format!("{{@const ...}} must consist of a single variable declaration\nhttps://svelte.dev/e/const_tag_invalid_expression"))
}

pub fn css_empty_declaration(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "css_empty_declaration", format!("Declaration cannot be empty\nhttps://svelte.dev/e/css_empty_declaration"))
}

pub fn css_expected_identifier(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "css_expected_identifier", format!("Expected a valid CSS identifier\nhttps://svelte.dev/e/css_expected_identifier"))
}

pub fn css_selector_invalid(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "css_selector_invalid", format!("Invalid selector\nhttps://svelte.dev/e/css_selector_invalid"))
}

pub fn debug_tag_invalid_arguments(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "debug_tag_invalid_arguments", format!("{{@debug ...}} arguments must be identifiers, not arbitrary expressions\nhttps://svelte.dev/e/debug_tag_invalid_arguments"))
}

pub fn declaration_tag_invalid_type(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "declaration_tag_invalid_type", format!("Declaration tags must be `let` or `const` declarations\nhttps://svelte.dev/e/declaration_tag_invalid_type"))
}

pub fn directive_invalid_value(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "directive_invalid_value", format!("Directive value must be a JavaScript expression enclosed in curly braces\nhttps://svelte.dev/e/directive_invalid_value"))
}

pub fn directive_missing_name(node: impl Into<Loc>, r#type: &str) -> CompileError {
	CompileError::new(node.into(), "directive_missing_name", format!("`{}` name cannot be empty\nhttps://svelte.dev/e/directive_missing_name", r#type))
}

pub fn element_invalid_closing_tag(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "element_invalid_closing_tag", format!("`</{}>` attempted to close an element that was not open\nhttps://svelte.dev/e/element_invalid_closing_tag", name))
}

pub fn element_invalid_closing_tag_autoclosed(node: impl Into<Loc>, name: &str, reason: &str) -> CompileError {
	CompileError::new(node.into(), "element_invalid_closing_tag_autoclosed", format!("`</{}>` attempted to close element that was already automatically closed by `<{}>` (cannot nest `<{}>` inside `<{}>`)\nhttps://svelte.dev/e/element_invalid_closing_tag_autoclosed", name, reason, reason, name))
}

pub fn element_unclosed(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "element_unclosed", format!("`<{}>` was left open\nhttps://svelte.dev/e/element_unclosed", name))
}

pub fn expected_attribute_value(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "expected_attribute_value", format!("Expected attribute value\nhttps://svelte.dev/e/expected_attribute_value"))
}

pub fn expected_block_type(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "expected_block_type", format!("Expected 'if', 'each', 'await', 'key' or 'snippet'\nhttps://svelte.dev/e/expected_block_type"))
}

pub fn expected_identifier(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "expected_identifier", format!("Expected an identifier\nhttps://svelte.dev/e/expected_identifier"))
}

pub fn expected_pattern(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "expected_pattern", format!("Expected identifier or destructure pattern\nhttps://svelte.dev/e/expected_pattern"))
}

pub fn expected_tag(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "expected_tag", format!("Expected 'html', 'render', 'attach', 'const', or 'debug'\nhttps://svelte.dev/e/expected_tag"))
}

pub fn expected_token(node: impl Into<Loc>, token: &str) -> CompileError {
	CompileError::new(node.into(), "expected_token", format!("Expected token {}\nhttps://svelte.dev/e/expected_token", token))
}

pub fn expected_whitespace(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "expected_whitespace", format!("Expected whitespace\nhttps://svelte.dev/e/expected_whitespace"))
}

pub fn js_parse_error(node: impl Into<Loc>, message: &str) -> CompileError {
	CompileError::new(node.into(), "js_parse_error", format!("{}\nhttps://svelte.dev/e/js_parse_error", message))
}

pub fn render_tag_invalid_expression(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "render_tag_invalid_expression", format!("`{{@render ...}}` tags can only contain call expressions\nhttps://svelte.dev/e/render_tag_invalid_expression"))
}

pub fn script_duplicate(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "script_duplicate", format!("A component can have a single top-level `<script>` element and/or a single top-level `<script module>` element\nhttps://svelte.dev/e/script_duplicate"))
}

pub fn script_invalid_attribute_value(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "script_invalid_attribute_value", format!("If the `{}` attribute is supplied, it must be a boolean attribute\nhttps://svelte.dev/e/script_invalid_attribute_value", name))
}

pub fn script_invalid_context(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "script_invalid_context", format!("If the context attribute is supplied, its value must be \"module\"\nhttps://svelte.dev/e/script_invalid_context"))
}

pub fn script_reserved_attribute(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "script_reserved_attribute", format!("The `{}` attribute is reserved and cannot be used\nhttps://svelte.dev/e/script_reserved_attribute", name))
}

pub fn style_duplicate(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "style_duplicate", format!("A component can have a single top-level `<style>` element\nhttps://svelte.dev/e/style_duplicate"))
}

pub fn svelte_component_invalid_this(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "svelte_component_invalid_this", format!("Invalid component definition — must be an `{{expression}}`\nhttps://svelte.dev/e/svelte_component_invalid_this"))
}

pub fn svelte_component_missing_this(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "svelte_component_missing_this", format!("`<svelte:component>` must have a 'this' attribute\nhttps://svelte.dev/e/svelte_component_missing_this"))
}

pub fn svelte_element_missing_this(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "svelte_element_missing_this", format!("`<svelte:element>` must have a 'this' attribute with a value\nhttps://svelte.dev/e/svelte_element_missing_this"))
}

pub fn svelte_meta_duplicate(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "svelte_meta_duplicate", format!("A component can only have one `<{}>` element\nhttps://svelte.dev/e/svelte_meta_duplicate", name))
}

pub fn svelte_meta_invalid_content(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "svelte_meta_invalid_content", format!("<{}> cannot have children\nhttps://svelte.dev/e/svelte_meta_invalid_content", name))
}

pub fn svelte_meta_invalid_placement(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "svelte_meta_invalid_placement", format!("`<{}>` tags cannot be inside elements or blocks\nhttps://svelte.dev/e/svelte_meta_invalid_placement", name))
}

pub fn svelte_meta_invalid_tag(node: impl Into<Loc>, list: &str) -> CompileError {
	CompileError::new(node.into(), "svelte_meta_invalid_tag", format!("Valid `<svelte:...>` tag names are {}\nhttps://svelte.dev/e/svelte_meta_invalid_tag", list))
}

pub fn svelte_options_deprecated_tag(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "svelte_options_deprecated_tag", format!("\"tag\" option is deprecated — use \"customElement\" instead\nhttps://svelte.dev/e/svelte_options_deprecated_tag"))
}

pub fn svelte_options_invalid_attribute(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "svelte_options_invalid_attribute", format!("`<svelte:options>` can only receive static attributes\nhttps://svelte.dev/e/svelte_options_invalid_attribute"))
}

pub fn svelte_options_invalid_attribute_value(node: impl Into<Loc>, list: &str) -> CompileError {
	CompileError::new(node.into(), "svelte_options_invalid_attribute_value", format!("Value must be {}, if specified\nhttps://svelte.dev/e/svelte_options_invalid_attribute_value", list))
}

pub fn svelte_options_invalid_customelement(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "svelte_options_invalid_customelement", format!("\"customElement\" must be a string literal defining a valid custom element name or an object of the form {{ tag?: string; shadow?: \"open\" | \"none\" | `ShadowRootInit`; props?: {{ [key: string]: {{ attribute?: string; reflect?: boolean; type: .. }} }} }}\nhttps://svelte.dev/e/svelte_options_invalid_customelement"))
}

pub fn svelte_options_invalid_customelement_props(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "svelte_options_invalid_customelement_props", format!("\"props\" must be a statically analyzable object literal of the form \"{{ [key: string]: {{ attribute?: string; reflect?: boolean; type?: \"String\" | \"Boolean\" | \"Number\" | \"Array\" | \"Object\" }}\"\nhttps://svelte.dev/e/svelte_options_invalid_customelement_props"))
}

pub fn svelte_options_invalid_customelement_shadow(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "svelte_options_invalid_customelement_shadow", format!("\"shadow\" must be either \"open\", \"none\" or `ShadowRootInit` object.\nhttps://svelte.dev/e/svelte_options_invalid_customelement_shadow"))
}

pub fn svelte_options_invalid_tagname(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "svelte_options_invalid_tagname", format!("Tag name must be lowercase and hyphenated\nhttps://svelte.dev/e/svelte_options_invalid_tagname"))
}

pub fn svelte_options_reserved_tagname(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "svelte_options_reserved_tagname", format!("Tag name is reserved\nhttps://svelte.dev/e/svelte_options_reserved_tagname"))
}

pub fn svelte_options_unknown_attribute(node: impl Into<Loc>, name: &str) -> CompileError {
	CompileError::new(node.into(), "svelte_options_unknown_attribute", format!("`<svelte:options>` unknown attribute '{}'\nhttps://svelte.dev/e/svelte_options_unknown_attribute", name))
}

pub fn tag_invalid_name(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "tag_invalid_name", format!("Expected a valid element or component name. Components must have a valid variable name or dot notation expression\nhttps://svelte.dev/e/tag_invalid_name"))
}

pub fn tag_invalid_placement(node: impl Into<Loc>, name: &str, location: &str) -> CompileError {
	CompileError::new(node.into(), "tag_invalid_placement", format!("{{@{} ...}} tag cannot be {}\nhttps://svelte.dev/e/tag_invalid_placement", name, location))
}

pub fn unexpected_eof(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "unexpected_eof", format!("Unexpected end of input\nhttps://svelte.dev/e/unexpected_eof"))
}

pub fn unexpected_reserved_word(node: impl Into<Loc>, word: &str) -> CompileError {
	CompileError::new(node.into(), "unexpected_reserved_word", format!("'{}' is a reserved word in JavaScript and cannot be used here\nhttps://svelte.dev/e/unexpected_reserved_word", word))
}

pub fn unterminated_string_constant(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "unterminated_string_constant", format!("Unterminated string constant\nhttps://svelte.dev/e/unterminated_string_constant"))
}

pub fn void_element_invalid_content(node: impl Into<Loc>) -> CompileError {
	CompileError::new(node.into(), "void_element_invalid_content", format!("Void elements cannot have children or closing tags\nhttps://svelte.dev/e/void_element_invalid_content"))
}

